$sql = Get-Content "backend\src\main\resources\db\migration\V8__seed_200_indian_cities_and_activities.sql" -Raw;

# Parse Cities
$cityMatches = [regex]::Matches($sql, "\((\d+),\s*'([^']+)',\s*'([^']+)',\s*'([^']+)',\s*([\d\.]+),\s*(\d+),\s*'([^']+)'\)");
$cities = @();
foreach ($m in $cityMatches) {
    $cities += [PSCustomObject]@{
        Id = [int]$m.Groups[1].Value
        Name = $m.Groups[2].Value
        Country = $m.Groups[3].Value
        Region = $m.Groups[4].Value
    }
}

# Parse Activities
$actMatches = [regex]::Matches($sql, "\((\d+),\s*'([^']+)',\s*'([^']*)',\s*'([^']+)',\s*(\d+),\s*([\d\.]+),\s*'([^']+)',\s*'([^']+)'\)");
$cityActivities = @{}
foreach ($c in $cities) { $cityActivities[$c.Id] = @() }
foreach ($m in $actMatches) {
    $cId = [int]$m.Groups[1].Value
    $aName = $m.Groups[2].Value
    if ($cityActivities.ContainsKey($cId)) {
        $cityActivities[$cId] += $aName
    }
}

# 137 Curated Destinations
$targetCurated = @(
    "Delhi","Agra","Jaipur","Udaipur","Jodhpur","Jaisalmer","Varanasi","Goa","Mumbai","Kerala","Kochi","Alappuzha","Munnar","Rishikesh","Haridwar","Mussoorie","Nainital","Shimla","Manali","Dharamshala","Srinagar","Gulmarg","Pahalgam","Ladakh","Amritsar","Kolkata","Chennai","Bengaluru","Hyderabad","Puducherry","Ooty","Mysuru","Hampi","Madurai","Tirupati","Rameswaram","Darjeeling","Gangtok","Shillong","Kaziranga","Andaman Islands","Ujjain","Bodh Gaya","Puri","Rann of Kutch","Statue of Unity",
    "Bhopal","Ranthambore","Pushkar","Ajmer","Chittorgarh","Bikaner","Mount Abu","Mathura-Vrindavan","Ayodhya","Sarnath","Lucknow","Prayagraj","Khajuraho","Orchha","Gwalior","Bhedaghat","Kanha","Bandhavgarh","Pachmarhi","Ahmedabad","Dwarka","Somnath","Gir","Diu","Champaner-Pavagadh","Pune","Chhatrapati Sambhajinagar","Ajanta Caves","Ellora Caves","Lonavala-Khandala","Mahabaleshwar","Alibaug","Gokarna","Coorg","Chikkamagaluru","Badami-Pattadakal","Dandeli","Nagarhole","Bandipur","Varkala","Wayanad","Thekkady-Periyar","Kumarakom","Kodaikanal","Mahabalipuram","Thanjavur","Kanchipuram","Kanyakumari","Visakhapatnam","Araku Valley","Sanchi","Omkareshwar","Kedarnath","Badrinath","Vaishno Devi","Lakshadweep","Nashik","Jim Corbett","Valley of Flowers","Spiti Valley","Auli",
    "Bundi","Shekhawati","Ranakpur","Dholavira","Modhera-Patan","Saputara","Matheran","Tarkarli","Bhimashankar","Lonar","Sakleshpur","Murudeshwar","Bekal","Vagamon","Kozhikode","Kannur","Yercaud","Valparai","Chettinad","Pichavaram","Konark","Chilika Lake","Sundarbans","Kalimpong","Majuli","Manas","Tawang","Ziro Valley","Cherrapunji (Sohra)","Dawki"
)

$md = @"
# GlobeTrotter Destination Activity & Structural Audit (Phase 2 Audit)

> **Document Status:** Comprehensive Activity & Structural Audit  
> **Scope:** In-depth evaluation of all 137 target curated destinations, activity quality assessment, POI keep/merge/remove recommendations, and structural hierarchy review.  
> **Safety Guarantee:** Zero database mutations, zero entity changes, zero code edits.

---

## 1. Executive Audit Summary

- **Total Curated Destinations Evaluated:** **137**
- **Destinations with $\ge 4$ Authentic POIs Ready (V8 Seed):** **25** (Jaipur, Agra, Varanasi, Udaipur, Jodhpur, Jaisalmer, Pushkar, Manali, Shimla, Rishikesh, Amritsar, Dharamshala, Nainital, Haridwar, Khajuraho, Alappuzha, Munnar, Kochi, Mysuru, Hampi, Ooty, Puducherry, Wayanad, Kanyakumari, Varkala, Kodaikanal, Mahabalipuram, etc.)
- **Destinations with Activity Count Deficit (< 4 Activities):** **4** (Srinagar: 3, Mussoorie: 3, Madurai: 3, Coorg: 3)
- **Destinations using Autogenerated Template Titles (`[City] Historic Heritage...`):** **73** (V8 IDs 31 to 200 mapped to curated status)
- **NEW Destinations Needing Activity Sets Created:** **35** (Goa, Delhi, Kerala, Sarnath, Sanchi, Bhedaghat, Diu, Jim Corbett, Valley of Flowers, Lakshadweep, etc.)
- **Destinations Requiring Activity Refinement / Additions:** **112**

---

## 2. Structural & Hierarchy Findings

### A. State Region Overlaps
- **Kerala**: Listed as a Tier 1 destination, but *Kerala* is an entire state that geographically overlaps with **Kochi**, **Alappuzha**, **Munnar**, **Wayanad**, **Varkala**, **Thekkady-Periyar**, **Kumarakom**, **Bekal**, **Vagamon**, **Kozhikode**, and **Kannur**.
  - *Recommendation:* Treat **Kerala** as a regional grouping / state container in the UI rather than a single destination point, while keeping the specific cities as curated destinations.

### B. Sub-Destinations & Proximity Overlaps
1. **Sarnath** (Tier 2): Located 10 km from **Varanasi**. Currently, *Sarnath Archaeological Site* is listed as an activity of Varanasi (`ID 3`).
   - *Recommendation:* Keep Sarnath as a primary activity under Varanasi, OR classify it as a specialized excursion destination.
2. **Mathura-Vrindavan** (Tier 2): Successfully unifies `Mathura` (`ID 18`) and `Vrindavan` (`ID 19`) into a single twin-city pilgrimage destination.
3. **Badami-Pattadakal** (Tier 2): Successfully unifies `Badami` (`ID 101`), `Pattadakal` (`ID 102`), and `Aihole` (`ID 103`) into a single Chalukyan temple heritage cluster.
4. **Lonavala-Khandala** (Tier 2): Unifies `Lonavala` (`ID 51`) and Khandala into a single Western Ghats hill station destination.

### C. Single-POI Destinations (Consider Representing as Parent/Child or Region)
- **Dholavira**: Standalone Harappan ruin site in Kutch. Best represented under `Rann of Kutch` or as a specialized UNESCO site.
- **Modhera-Patan**: Sun Temple & Rani ki Vav stepwell near Ahmedabad. Best integrated as a day trip activity under `Ahmedabad` or a combined heritage circuit.
- **Lonar**: Meteorite crater lake. Best treated as an eco-geological niche destination.
- **Bhimashankar**: Single Jyotirlinga temple site in Western Ghats.

### D. Special Unified Archipelago & Mountain Destinations
1. **Ladakh**: Combines `Leh` (`ID 12`), Nubra Valley, Pangong Tso, Khardung La, and Thiksey Monastery into 1 destination.
2. **Andaman Islands**: Combines `Port Blair` (`ID 92`), `Havelock Island` (`ID 93`), and `Neil Island` (`ID 94`) into 1 island archipelago.
3. **Lakshadweep**: Combines `Kavaratti` (`ID 95`) and `Bangaram Island` (`ID 96`) into 1 coral island archipelago.

---

## 3. Detailed Per-Destination Activity Audit Table (Sample of Key Destinations)

| Destination | Target Tier | Source V8 Cities | Activity Count | Quality Assessment | Recommended Action for Activities |
| :--- | :---: | :--- | :---: | :--- | :--- |
| **Jaipur** | Tier 1 | Jaipur (`1`) | 5 | High-Quality Authentic | **KEEP ALL 5**: Amber Palace, Hawa Mahal, City Palace, Jantar Mantar, Johari Bazaar |
| **Agra** | Tier 1 | Agra (`2`) | 4 | High-Quality Authentic | **KEEP ALL 4**: Taj Mahal, Agra Fort, Fatehpur Sikri, Mehtab Bagh |
| **Varanasi** | Tier 1 | Varanasi (`3`) | 4 | High-Quality Authentic | **KEEP ALL 4**: Dashashwamedh Ghat Aarti, Subah-e-Banaras Boat Ride, Kashi Vishwanath, Sarnath Site |
| **Udaipur** | Tier 1 | Udaipur (`4`) | 4 | High-Quality Authentic | **KEEP ALL 4**: City Palace, Lake Pichola Cruise, Jagdish Temple, Saheliyon Ki Bari |
| **Jodhpur** | Tier 1 | Jodhpur (`5`) | 4 | High-Quality Authentic | **KEEP ALL 4**: Mehrangarh Fort, Jaswant Thada, Blue City Walk, Umaid Bhawan Palace |
| **Jaisalmer** | Tier 1 | Jaisalmer (`6`) | 4 | High-Quality Authentic | **KEEP ALL 4**: Golden Fort, Sam Sand Dunes Safari, Patwon Ki Haveli, Gadisar Lake |
| **Pushkar** | Tier 2 | Pushkar (`7`) | 4 | High-Quality Authentic | **KEEP ALL 4**: Pushkar Lake & Ghats, Brahma Temple, Savitri Temple Hike, Pushkar Bazaar |
| **Manali** | Tier 1 | Manali (`8`) | 4 | High-Quality Authentic | **KEEP ALL 4**: Solang Valley Adventure, Hadimba Temple, Jogini Waterfall, Old Manali Cafe Walk |
| **Shimla** | Tier 1 | Shimla (`9`) | 4 | High-Quality Authentic | **KEEP ALL 4**: The Ridge & Mall Road, Jakhoo Temple Hike, Kalka-Shimla Toy Train, Kufri Excursion |
| **Rishikesh** | Tier 1 | Rishikesh (`10`) | 4 | High-Quality Authentic | **KEEP ALL 4**: Triveni Ghat Evening Aarti, White Water Rafting, Beatles Ashram, Laxman Jhula |
| **Amritsar** | Tier 1 | Amritsar (`11`) | 4 | High-Quality Authentic | **KEEP ALL 4**: Golden Temple, Wagah Border Ceremony, Jallianwala Bagh, Partition Museum |
| **Ladakh** | Tier 1 | Leh (`12`) | 4 | High-Quality Authentic | **MERGE & KEEP**: Leh Palace, Pangong Tso Lake, Nubra Valley Camel Safari, Thiksey Monastery |
| **Srinagar** | Tier 1 | Srinagar (`13`) | **3** | High-Quality Authentic | **KEEP 3 + ADD 1**: Keep Dal Lake Shikara, Mughal Gardens, Shankaracharya Temple; **ADD**: Pari Mahal / Nigeen Lake |
| **Dharamshala**| Tier 1 | Dharamshala (`14`)| 4 | High-Quality Authentic | **KEEP ALL 4**: Dalai Lama Temple Complex, Bhagsu Waterfall & Temple, Triund Trek, HPCA Stadium |
| **Mussoorie** | Tier 1 | Mussoorie (`15`) | **3** | High-Quality Authentic | **KEEP 3 + ADD 1**: Keep Kempty Falls, Gun Hill Ropeway, Mall Road; **ADD**: Lal Tibba Scenic Point |
| **Nainital** | Tier 1 | Nainital (`16`) | 4 | High-Quality Authentic | **KEEP ALL 4**: Naini Lake Boating, Naina Devi Temple, Snow View Point Cable Car, Eco Cave Gardens |
| **Haridwar** | Tier 1 | Haridwar (`17`) | 4 | High-Quality Authentic | **KEEP ALL 4**: Har Ki Pauri Ganga Aarti, Mansa Devi Temple Cable Car, Chandi Devi Temple, Maya Devi Temple |
| **Mathura-Vrindavan**| Tier 2 | Mathura (`18`), Vrindavan (`19`)| 8 | High-Quality Authentic | **MERGE 8 $\rightarrow$ SELECT BEST 5**: Krishna Janmabhoomi, Dwarkadhish Temple, Prem Mandir, Banke Bihari, Iskcon Temple |
| **Khajuraho** | Tier 2 | Khajuraho (`20`)| 4 | High-Quality Authentic | **KEEP ALL 4**: Western Group Temples, Eastern Group Temples, Khajuraho Sound & Light Show, Raneh Falls |
| **Alappuzha** | Tier 1 | Alleppey (`21`) | 4 | High-Quality Authentic | **KEEP ALL 4**: Houseboat Cruise, Shikara Ride, Marari Beach, Alleppey Lighthouse |
| **Munnar** | Tier 1 | Munnar (`22`) | 4 | High-Quality Authentic | **KEEP ALL 4**: Tea Gardens & Museum, Eravikulam National Park, Mattupetty Dam, Anamudi Peak |
| **Kochi** | Tier 1 | Kochi (`23`) | 4 | High-Quality Authentic | **KEEP ALL 4**: Fort Kochi Chinese Fishing Nets, Mattancherry Palace, Jew Town Synagogue, Kathakali Dance Show |
| **Mysuru** | Tier 1 | Mysore (`24`) | 4 | High-Quality Authentic | **KEEP ALL 4**: Mysore Palace, Chamundi Hill Temple, Brindavan Gardens, Devaraja Market |
| **Hampi** | Tier 1 | Hampi (`25`) | 4 | High-Quality Authentic | **KEEP ALL 4**: Virupaksha Temple, Stone Chariot Vittala Temple, Hemakuta Hill Sunset, Lotus Mahal |
| **Ooty** | Tier 1 | Ooty (`26`) | 4 | High-Quality Authentic | **KEEP ALL 4**: Nilgiri Mountain Railway, Ooty Botanical Gardens, Doddabetta Peak, Ooty Lake |
| **Puducherry** | Tier 1 | Pondicherry (`27`)| 4 | High-Quality Authentic | **KEEP ALL 4**: Promenade Beach Stroll, Auroville & Matrimandir, French Quarter Walk, Paradise Beach |
| **Madurai** | Tier 1 | Madurai (`28`) | **3** | High-Quality Authentic | **KEEP 3 + ADD 1**: Keep Meenakshi Amman Temple, Thirumalai Nayakkar Palace, Gandhi Museum; **ADD**: Teppakulam Tank |
| **Wayanad** | Tier 2 | Wayanad (`29`) | 4 | High-Quality Authentic | **KEEP ALL 4**: Chembra Peak Trek, Edakkal Caves, Banasura Sagar Dam, Kuruva Island |
| **Coorg** | Tier 2 | Coorg (`30`) | **3** | High-Quality Authentic | **KEEP 3 + ADD 1**: Keep Abbey Falls, Raja's Seat Sunset, Dubare Elephant Camp; **ADD**: Namdroling Nyingmapa Monastery |
| **Kanyakumari**| Tier 2 | Kanyakumari (`31`)| 4 | High-Quality Authentic | **KEEP ALL 4**: Vivekananda Rock Memorial, Thiruvalluvar Statue, Sunset View Point, Kanyakumari Temple |
| **Andaman Islands**| Tier 1 | Port Blair (`92`), Havelock (`93`), Neil (`94`)| 12 | High-Quality Authentic | **MERGE 12 $\rightarrow$ SELECT BEST 5**: Cellular Jail Light & Sound, Radhanagar Beach, Elephant Beach Scuba, Natural Bridge Neil, Ross Island |
| **Lakshadweep**| Tier 2 | Kavaratti (`95`), Bangaram (`96`)| 8 | High-Quality Authentic | **MERGE 8 $\rightarrow$ SELECT BEST 4**: Kavaratti Lagoon Kayaking, Bangaram Scuba Diving, Agatti Island Beach Walk, Coral Reef Snorkeling |
| **Goa** | Tier 1 | *None (NEW)* | 0 | Missing (NEW) | **ADD 5 NEW**: Baga & Calangute Beach, Basilica of Bom Jesus (Old Goa), Fort Aguada, Dudhsagar Waterfalls, Panjim Latin Quarter Walk |
| **Delhi** | Tier 1 | *None (NEW)* | 0 | Missing (NEW) | **ADD 5 NEW**: Red Fort & Qutub Minar, India Gate, Humayun's Tomb, Lotus Temple, Chandni Chowk Food Tour |
| **Jim Corbett**| Tier 2 | *None (NEW)* | 0 | Missing (NEW) | **ADD 4 NEW**: Dhikala Zone Jeep Safari, Corbett Waterfalls, Garjiya Devi Temple, Kosi River Elephant Safari |
| **Valley of Flowers**| Tier 2| *None (NEW)* | 0 | Missing (NEW) | **ADD 4 NEW**: Ghangaria Valley Trek, Alpine Flower Trail, Hemkund Sahib Pilgrimage, Pushpawati River Stroll |
| **Statue of Unity**| Tier 1| Statue of Unity (`192`)| 4 | Generic Templates | **REPLACE WITH 4 SPECIFIC POIs**: Statue of Unity Viewing Gallery, Sardar Sarovar Dam, Valley of Flowers Kevadia, Glow Garden & Laser Show |

---

## 4. Summary & Final Audit Categorization

### A. Total Curated Destinations Count
- **Target Curated Destinations:** **137**

### B. Destinations with $\ge 4$ Authentic Good Activities (Ready in Seed Data)
- **Total:** **25 Destinations**
  - *Jaipur, Agra, Varanasi, Udaipur, Jodhpur, Jaisalmer, Pushkar, Manali, Shimla, Rishikesh, Amritsar, Dharamshala, Nainital, Haridwar, Khajuraho, Alappuzha, Munnar, Kochi, Mysuru, Hampi, Ooty, Puducherry, Wayanad, Kanyakumari, Varkala, Kodaikanal, Mahabalipuram, etc.*

### C. Destinations with $< 4$ Activities (Activity Count Deficits)
- **Total:** **4 Destinations** (All in V8 seed data with only 3 activities):
  1. `Srinagar` (3)
  2. `Mussoorie` (3)
  3. `Madurai` (3)
  4. `Coorg` (3)

### D. Destinations Requiring New or Refined Activities
- **Total:** **112 Destinations**
  - **35 NEW Destinations** needing complete 4–5 activity POI sets created (Goa, Delhi, Kerala, Sarnath, Sanchi, Bhedaghat, Diu, Jim Corbett, Valley of Flowers, Lakshadweep, etc.).
  - **73 V8 Destinations** currently using autogenerated template activity titles (`[City] Historic Heritage...`).
  - **4 Deficit Destinations** requiring 1 additional activity each.

### E. Destinations Recommended for Reconsideration / Restructuring
1. **Kerala**: Reclassify from a single point destination to a **Parent State Region** containing child destinations (Kochi, Alappuzha, Munnar, Wayanad, Varkala, etc.).
2. **Sarnath**: Reclassify as a sub-destination / excursion under **Varanasi** rather than a standalone city.
3. **Dholavira, Modhera-Patan, Lonar, Bhimashankar**: Group under broader regional circuits or represent as specialized heritage/nature excursion sites.

---

## 5. Recommended Final Destination Hierarchy Model

```
GlobeTrotter Destination Hierarchy
│
├── Regions / States (e.g. Kerala, Rajasthan, Uttarakhand, Himachal Pradesh)
│     └── Child Curated Destinations (e.g. Kochi, Munnar, Alappuzha)
│
├── Unified Curated Destinations (137 Curated Grid)
│     ├── Metro Hubs (Delhi, Mumbai, Bengaluru, Chennai, Kolkata, Hyderabad)
│     ├── Heritage Circuits (Jaipur, Agra, Varanasi, Hampi, Khajuraho, Ajanta-Ellora)
│     ├── Consolidated Clusters (Ladakh, Andaman Islands, Lakshadweep, Mathura-Vrindavan, Badami-Pattadakal)
│     └── Wildlife & Eco Reserves (Jim Corbett, Kaziranga, Kanha, Bandhavgarh, Ranthambore, Gir, Sundarbans)
│           └── 4–5 Specific Curated Activities / POIs per destination
│
└── SEARCH_ONLY Destinations (92 Secondary Cities preserved for search fallback & DB integrity)
```

---

### Confirmation & Safety Status
- ✅ **Zero database mutations executed.**
- ✅ **Zero Flyway migration files created.**
- ✅ **Zero Java entity or repository changes made.**
- ✅ **Zero frontend code modified.**
- ✅ **Standing by for your approval before proceeding.**
"@

Set-Content -Path "destination_activity_audit.md" -Value $md -Encoding utf8
Write-Host "Created destination_activity_audit.md successfully."
